// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 账号信息
   * </pre>
   *
   * <code>.user.UserInfo user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <pre>
   * 账号信息
   * </pre>
   *
   * <code>.user.UserInfo user = 1;</code>
   * @return The user.
   */
  com.proto.user.UserInfo getUser();
  /**
   * <pre>
   * 账号信息
   * </pre>
   *
   * <code>.user.UserInfo user = 1;</code>
   */
  com.proto.user.UserInfoOrBuilder getUserOrBuilder();

  /**
   * <pre>
   * 多多账号昵称
   * </pre>
   *
   * <code>string Nickname = 2;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <pre>
   * 多多账号昵称
   * </pre>
   *
   * <code>string Nickname = 2;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <pre>
   * 加入队伍时间戳
   * </pre>
   *
   * <code>int64 joinTime = 3;</code>
   * @return The joinTime.
   */
  long getJoinTime();

  /**
   * <pre>
   * 队员准备状态
   * </pre>
   *
   * <code>.core.TeamMemberState state = 4;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * 队员准备状态
   * </pre>
   *
   * <code>.core.TeamMemberState state = 4;</code>
   * @return The state.
   */
  com.zqproto.core.TeamMemberState getState();
}
