// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

public interface CreateTeamReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.CreateTeamReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return Whether the res field is set.
   */
  boolean hasRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return The res.
   */
  com.proto.comm.CommReply getRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   */
  com.proto.comm.CommReplyOrBuilder getResOrBuilder();

  /**
   * <pre>
   * 多多和浩方用户信息
   * </pre>
   *
   * <code>.core.Account account = 2;</code>
   * @return Whether the account field is set.
   */
  boolean hasAccount();
  /**
   * <pre>
   * 多多和浩方用户信息
   * </pre>
   *
   * <code>.core.Account account = 2;</code>
   * @return The account.
   */
  com.zqproto.core.Account getAccount();
  /**
   * <pre>
   * 多多和浩方用户信息
   * </pre>
   *
   * <code>.core.Account account = 2;</code>
   */
  com.zqproto.core.AccountOrBuilder getAccountOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>.core.TeamInfo teamInfo = 4;</code>
   * @return Whether the teamInfo field is set.
   */
  boolean hasTeamInfo();
  /**
   * <pre>
   * </pre>
   *
   * <code>.core.TeamInfo teamInfo = 4;</code>
   * @return The teamInfo.
   */
  com.zqproto.core.TeamInfo getTeamInfo();
  /**
   * <pre>
   * </pre>
   *
   * <code>.core.TeamInfo teamInfo = 4;</code>
   */
  com.zqproto.core.TeamInfoOrBuilder getTeamInfoOrBuilder();
}
