// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

/**
 * <pre>
 * 加入队伍
 * </pre>
 *
 * Protobuf type {@code core.JoinTeamRequest}
 */
public  final class JoinTeamRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:core.JoinTeamRequest)
    JoinTeamRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JoinTeamRequest.newBuilder() to construct.
  private JoinTeamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JoinTeamRequest() {
    traceId_ = "";
    teamId_ = "";
    myTeamId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JoinTeamRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JoinTeamRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            traceId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            teamId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            myTeamId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zqproto.core.Core.internal_static_core_JoinTeamRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zqproto.core.Core.internal_static_core_JoinTeamRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zqproto.core.JoinTeamRequest.class, com.zqproto.core.JoinTeamRequest.Builder.class);
  }

  public static final int TRACEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object traceId_;
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 1;</code>
   * @return The traceId.
   */
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 1;</code>
   * @return The bytes for traceId.
   */
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEAMID_FIELD_NUMBER = 2;
  private volatile java.lang.Object teamId_;
  /**
   * <pre>
   * 要加入的队伍编号
   * </pre>
   *
   * <code>string teamId = 2;</code>
   * @return The teamId.
   */
  public java.lang.String getTeamId() {
    java.lang.Object ref = teamId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      teamId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 要加入的队伍编号
   * </pre>
   *
   * <code>string teamId = 2;</code>
   * @return The bytes for teamId.
   */
  public com.google.protobuf.ByteString
      getTeamIdBytes() {
    java.lang.Object ref = teamId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      teamId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MYTEAMID_FIELD_NUMBER = 3;
  private volatile java.lang.Object myTeamId_;
  /**
   * <pre>
   * 自己的队伍编号
   * </pre>
   *
   * <code>string myTeamId = 3;</code>
   * @return The myTeamId.
   */
  public java.lang.String getMyTeamId() {
    java.lang.Object ref = myTeamId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      myTeamId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 自己的队伍编号
   * </pre>
   *
   * <code>string myTeamId = 3;</code>
   * @return The bytes for myTeamId.
   */
  public com.google.protobuf.ByteString
      getMyTeamIdBytes() {
    java.lang.Object ref = myTeamId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      myTeamId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTraceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceId_);
    }
    if (!getTeamIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teamId_);
    }
    if (!getMyTeamIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, myTeamId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTraceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceId_);
    }
    if (!getTeamIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teamId_);
    }
    if (!getMyTeamIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, myTeamId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zqproto.core.JoinTeamRequest)) {
      return super.equals(obj);
    }
    com.zqproto.core.JoinTeamRequest other = (com.zqproto.core.JoinTeamRequest) obj;

    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getTeamId()
        .equals(other.getTeamId())) return false;
    if (!getMyTeamId()
        .equals(other.getMyTeamId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + TEAMID_FIELD_NUMBER;
    hash = (53 * hash) + getTeamId().hashCode();
    hash = (37 * hash) + MYTEAMID_FIELD_NUMBER;
    hash = (53 * hash) + getMyTeamId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zqproto.core.JoinTeamRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zqproto.core.JoinTeamRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zqproto.core.JoinTeamRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zqproto.core.JoinTeamRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zqproto.core.JoinTeamRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 加入队伍
   * </pre>
   *
   * Protobuf type {@code core.JoinTeamRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.JoinTeamRequest)
      com.zqproto.core.JoinTeamRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zqproto.core.Core.internal_static_core_JoinTeamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zqproto.core.Core.internal_static_core_JoinTeamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zqproto.core.JoinTeamRequest.class, com.zqproto.core.JoinTeamRequest.Builder.class);
    }

    // Construct using com.zqproto.core.JoinTeamRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      traceId_ = "";

      teamId_ = "";

      myTeamId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zqproto.core.Core.internal_static_core_JoinTeamRequest_descriptor;
    }

    @java.lang.Override
    public com.zqproto.core.JoinTeamRequest getDefaultInstanceForType() {
      return com.zqproto.core.JoinTeamRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.zqproto.core.JoinTeamRequest build() {
      com.zqproto.core.JoinTeamRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zqproto.core.JoinTeamRequest buildPartial() {
      com.zqproto.core.JoinTeamRequest result = new com.zqproto.core.JoinTeamRequest(this);
      result.traceId_ = traceId_;
      result.teamId_ = teamId_;
      result.myTeamId_ = myTeamId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zqproto.core.JoinTeamRequest) {
        return mergeFrom((com.zqproto.core.JoinTeamRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zqproto.core.JoinTeamRequest other) {
      if (other == com.zqproto.core.JoinTeamRequest.getDefaultInstance()) return this;
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        onChanged();
      }
      if (!other.getTeamId().isEmpty()) {
        teamId_ = other.teamId_;
        onChanged();
      }
      if (!other.getMyTeamId().isEmpty()) {
        myTeamId_ = other.myTeamId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zqproto.core.JoinTeamRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zqproto.core.JoinTeamRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 1;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 1;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 1;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      
      traceId_ = getDefaultInstance().getTraceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 1;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object teamId_ = "";
    /**
     * <pre>
     * 要加入的队伍编号
     * </pre>
     *
     * <code>string teamId = 2;</code>
     * @return The teamId.
     */
    public java.lang.String getTeamId() {
      java.lang.Object ref = teamId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teamId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 要加入的队伍编号
     * </pre>
     *
     * <code>string teamId = 2;</code>
     * @return The bytes for teamId.
     */
    public com.google.protobuf.ByteString
        getTeamIdBytes() {
      java.lang.Object ref = teamId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 要加入的队伍编号
     * </pre>
     *
     * <code>string teamId = 2;</code>
     * @param value The teamId to set.
     * @return This builder for chaining.
     */
    public Builder setTeamId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      teamId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要加入的队伍编号
     * </pre>
     *
     * <code>string teamId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeamId() {
      
      teamId_ = getDefaultInstance().getTeamId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要加入的队伍编号
     * </pre>
     *
     * <code>string teamId = 2;</code>
     * @param value The bytes for teamId to set.
     * @return This builder for chaining.
     */
    public Builder setTeamIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      teamId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object myTeamId_ = "";
    /**
     * <pre>
     * 自己的队伍编号
     * </pre>
     *
     * <code>string myTeamId = 3;</code>
     * @return The myTeamId.
     */
    public java.lang.String getMyTeamId() {
      java.lang.Object ref = myTeamId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        myTeamId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 自己的队伍编号
     * </pre>
     *
     * <code>string myTeamId = 3;</code>
     * @return The bytes for myTeamId.
     */
    public com.google.protobuf.ByteString
        getMyTeamIdBytes() {
      java.lang.Object ref = myTeamId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        myTeamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 自己的队伍编号
     * </pre>
     *
     * <code>string myTeamId = 3;</code>
     * @param value The myTeamId to set.
     * @return This builder for chaining.
     */
    public Builder setMyTeamId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      myTeamId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自己的队伍编号
     * </pre>
     *
     * <code>string myTeamId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMyTeamId() {
      
      myTeamId_ = getDefaultInstance().getMyTeamId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自己的队伍编号
     * </pre>
     *
     * <code>string myTeamId = 3;</code>
     * @param value The bytes for myTeamId to set.
     * @return This builder for chaining.
     */
    public Builder setMyTeamIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      myTeamId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:core.JoinTeamRequest)
  }

  // @@protoc_insertion_point(class_scope:core.JoinTeamRequest)
  private static final com.zqproto.core.JoinTeamRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zqproto.core.JoinTeamRequest();
  }

  public static com.zqproto.core.JoinTeamRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinTeamRequest>
      PARSER = new com.google.protobuf.AbstractParser<JoinTeamRequest>() {
    @java.lang.Override
    public JoinTeamRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JoinTeamRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JoinTeamRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinTeamRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zqproto.core.JoinTeamRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

