// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

public interface JoinTeamReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.JoinTeamReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return Whether the res field is set.
   */
  boolean hasRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return The res.
   */
  com.proto.comm.CommReply getRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   */
  com.proto.comm.CommReplyOrBuilder getResOrBuilder();

  /**
   * <pre>
   * 返回加入成功后的队伍信息
   * </pre>
   *
   * <code>.core.TeamInfo teamInfo = 2;</code>
   * @return Whether the teamInfo field is set.
   */
  boolean hasTeamInfo();
  /**
   * <pre>
   * 返回加入成功后的队伍信息
   * </pre>
   *
   * <code>.core.TeamInfo teamInfo = 2;</code>
   * @return The teamInfo.
   */
  com.zqproto.core.TeamInfo getTeamInfo();
  /**
   * <pre>
   * 返回加入成功后的队伍信息
   * </pre>
   *
   * <code>.core.TeamInfo teamInfo = 2;</code>
   */
  com.zqproto.core.TeamInfoOrBuilder getTeamInfoOrBuilder();
}
