// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

public interface KickMemberReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.KickMemberReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return Whether the res field is set.
   */
  boolean hasRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return The res.
   */
  com.proto.comm.CommReply getRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   */
  com.proto.comm.CommReplyOrBuilder getResOrBuilder();

  /**
   * <pre>
   * 被踢的用户ID
   * </pre>
   *
   * <code>repeated uint32 kickedUid = 2;</code>
   * @return A list containing the kickedUid.
   */
  java.util.List<java.lang.Integer> getKickedUidList();
  /**
   * <pre>
   * 被踢的用户ID
   * </pre>
   *
   * <code>repeated uint32 kickedUid = 2;</code>
   * @return The count of kickedUid.
   */
  int getKickedUidCount();
  /**
   * <pre>
   * 被踢的用户ID
   * </pre>
   *
   * <code>repeated uint32 kickedUid = 2;</code>
   * @param index The index of the element to return.
   * @return The kickedUid at the given index.
   */
  int getKickedUid(int index);
}
