// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

/**
 * Protobuf type {@code core.LeaveTeamReply}
 */
public  final class LeaveTeamReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:core.LeaveTeamReply)
    LeaveTeamReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LeaveTeamReply.newBuilder() to construct.
  private LeaveTeamReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LeaveTeamReply() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LeaveTeamReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LeaveTeamReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.proto.comm.CommReply.Builder subBuilder = null;
            if (res_ != null) {
              subBuilder = res_.toBuilder();
            }
            res_ = input.readMessage(com.proto.comm.CommReply.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(res_);
              res_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zqproto.core.Core.internal_static_core_LeaveTeamReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zqproto.core.Core.internal_static_core_LeaveTeamReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zqproto.core.LeaveTeamReply.class, com.zqproto.core.LeaveTeamReply.Builder.class);
  }

  public static final int RES_FIELD_NUMBER = 1;
  private com.proto.comm.CommReply res_;
  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return Whether the res field is set.
   */
  public boolean hasRes() {
    return res_ != null;
  }
  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return The res.
   */
  public com.proto.comm.CommReply getRes() {
    return res_ == null ? com.proto.comm.CommReply.getDefaultInstance() : res_;
  }
  /**
   * <code>.comm.CommReply res = 1;</code>
   */
  public com.proto.comm.CommReplyOrBuilder getResOrBuilder() {
    return getRes();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (res_ != null) {
      output.writeMessage(1, getRes());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (res_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRes());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zqproto.core.LeaveTeamReply)) {
      return super.equals(obj);
    }
    com.zqproto.core.LeaveTeamReply other = (com.zqproto.core.LeaveTeamReply) obj;

    if (hasRes() != other.hasRes()) return false;
    if (hasRes()) {
      if (!getRes()
          .equals(other.getRes())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRes()) {
      hash = (37 * hash) + RES_FIELD_NUMBER;
      hash = (53 * hash) + getRes().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zqproto.core.LeaveTeamReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zqproto.core.LeaveTeamReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zqproto.core.LeaveTeamReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zqproto.core.LeaveTeamReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zqproto.core.LeaveTeamReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.LeaveTeamReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.LeaveTeamReply)
      com.zqproto.core.LeaveTeamReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zqproto.core.Core.internal_static_core_LeaveTeamReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zqproto.core.Core.internal_static_core_LeaveTeamReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zqproto.core.LeaveTeamReply.class, com.zqproto.core.LeaveTeamReply.Builder.class);
    }

    // Construct using com.zqproto.core.LeaveTeamReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resBuilder_ == null) {
        res_ = null;
      } else {
        res_ = null;
        resBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zqproto.core.Core.internal_static_core_LeaveTeamReply_descriptor;
    }

    @java.lang.Override
    public com.zqproto.core.LeaveTeamReply getDefaultInstanceForType() {
      return com.zqproto.core.LeaveTeamReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.zqproto.core.LeaveTeamReply build() {
      com.zqproto.core.LeaveTeamReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zqproto.core.LeaveTeamReply buildPartial() {
      com.zqproto.core.LeaveTeamReply result = new com.zqproto.core.LeaveTeamReply(this);
      if (resBuilder_ == null) {
        result.res_ = res_;
      } else {
        result.res_ = resBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zqproto.core.LeaveTeamReply) {
        return mergeFrom((com.zqproto.core.LeaveTeamReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zqproto.core.LeaveTeamReply other) {
      if (other == com.zqproto.core.LeaveTeamReply.getDefaultInstance()) return this;
      if (other.hasRes()) {
        mergeRes(other.getRes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zqproto.core.LeaveTeamReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zqproto.core.LeaveTeamReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.proto.comm.CommReply res_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.comm.CommReply, com.proto.comm.CommReply.Builder, com.proto.comm.CommReplyOrBuilder> resBuilder_;
    /**
     * <code>.comm.CommReply res = 1;</code>
     * @return Whether the res field is set.
     */
    public boolean hasRes() {
      return resBuilder_ != null || res_ != null;
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     * @return The res.
     */
    public com.proto.comm.CommReply getRes() {
      if (resBuilder_ == null) {
        return res_ == null ? com.proto.comm.CommReply.getDefaultInstance() : res_;
      } else {
        return resBuilder_.getMessage();
      }
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     */
    public Builder setRes(com.proto.comm.CommReply value) {
      if (resBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        res_ = value;
        onChanged();
      } else {
        resBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     */
    public Builder setRes(
        com.proto.comm.CommReply.Builder builderForValue) {
      if (resBuilder_ == null) {
        res_ = builderForValue.build();
        onChanged();
      } else {
        resBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     */
    public Builder mergeRes(com.proto.comm.CommReply value) {
      if (resBuilder_ == null) {
        if (res_ != null) {
          res_ =
            com.proto.comm.CommReply.newBuilder(res_).mergeFrom(value).buildPartial();
        } else {
          res_ = value;
        }
        onChanged();
      } else {
        resBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     */
    public Builder clearRes() {
      if (resBuilder_ == null) {
        res_ = null;
        onChanged();
      } else {
        res_ = null;
        resBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     */
    public com.proto.comm.CommReply.Builder getResBuilder() {
      
      onChanged();
      return getResFieldBuilder().getBuilder();
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     */
    public com.proto.comm.CommReplyOrBuilder getResOrBuilder() {
      if (resBuilder_ != null) {
        return resBuilder_.getMessageOrBuilder();
      } else {
        return res_ == null ?
            com.proto.comm.CommReply.getDefaultInstance() : res_;
      }
    }
    /**
     * <code>.comm.CommReply res = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.comm.CommReply, com.proto.comm.CommReply.Builder, com.proto.comm.CommReplyOrBuilder> 
        getResFieldBuilder() {
      if (resBuilder_ == null) {
        resBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.proto.comm.CommReply, com.proto.comm.CommReply.Builder, com.proto.comm.CommReplyOrBuilder>(
                getRes(),
                getParentForChildren(),
                isClean());
        res_ = null;
      }
      return resBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:core.LeaveTeamReply)
  }

  // @@protoc_insertion_point(class_scope:core.LeaveTeamReply)
  private static final com.zqproto.core.LeaveTeamReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zqproto.core.LeaveTeamReply();
  }

  public static com.zqproto.core.LeaveTeamReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LeaveTeamReply>
      PARSER = new com.google.protobuf.AbstractParser<LeaveTeamReply>() {
    @java.lang.Override
    public LeaveTeamReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LeaveTeamReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LeaveTeamReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LeaveTeamReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zqproto.core.LeaveTeamReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

