// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

public interface LeaveTeamReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.LeaveTeamReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return Whether the res field is set.
   */
  boolean hasRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   * @return The res.
   */
  com.proto.comm.CommReply getRes();
  /**
   * <code>.comm.CommReply res = 1;</code>
   */
  com.proto.comm.CommReplyOrBuilder getResOrBuilder();
}
