// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

/**
 * <pre>
 * 队伍信息，成员列表刷新动作
 * </pre>
 *
 * Protobuf enum {@code core.TeamInfoAction}
 */
public enum TeamInfoAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Nothing = 0;</code>
   */
  Nothing(0),
  /**
   * <code>All = 1;</code>
   */
  All(1),
  /**
   * <code>Add = 2;</code>
   */
  Add(2),
  /**
   * <code>Del = 3;</code>
   */
  Del(3),
  /**
   * <code>Update = 4;</code>
   */
  Update(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Nothing = 0;</code>
   */
  public static final int Nothing_VALUE = 0;
  /**
   * <code>All = 1;</code>
   */
  public static final int All_VALUE = 1;
  /**
   * <code>Add = 2;</code>
   */
  public static final int Add_VALUE = 2;
  /**
   * <code>Del = 3;</code>
   */
  public static final int Del_VALUE = 3;
  /**
   * <code>Update = 4;</code>
   */
  public static final int Update_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TeamInfoAction valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TeamInfoAction forNumber(int value) {
    switch (value) {
      case 0: return Nothing;
      case 1: return All;
      case 2: return Add;
      case 3: return Del;
      case 4: return Update;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TeamInfoAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TeamInfoAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TeamInfoAction>() {
          public TeamInfoAction findValueByNumber(int number) {
            return TeamInfoAction.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.zqproto.core.Core.getDescriptor().getEnumTypes().get(2);
  }

  private static final TeamInfoAction[] VALUES = values();

  public static TeamInfoAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TeamInfoAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:core.TeamInfoAction)
}

