// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/teamdef.proto

package com.zqproto.core;

/**
 * <pre>
 * 队员状态
 * </pre>
 *
 * Protobuf enum {@code core.TeamMemberState}
 */
public enum TeamMemberState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 空闲状态
   * </pre>
   *
   * <code>Idle = 0;</code>
   */
  Idle(0),
  /**
   * <pre>
   * 准备状态
   * </pre>
   *
   * <code>Ready = 1;</code>
   */
  Ready(1),
  /**
   * <pre>
   * 游戏中
   * </pre>
   *
   * <code>InGame = 2;</code>
   */
  InGame(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 空闲状态
   * </pre>
   *
   * <code>Idle = 0;</code>
   */
  public static final int Idle_VALUE = 0;
  /**
   * <pre>
   * 准备状态
   * </pre>
   *
   * <code>Ready = 1;</code>
   */
  public static final int Ready_VALUE = 1;
  /**
   * <pre>
   * 游戏中
   * </pre>
   *
   * <code>InGame = 2;</code>
   */
  public static final int InGame_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TeamMemberState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TeamMemberState forNumber(int value) {
    switch (value) {
      case 0: return Idle;
      case 1: return Ready;
      case 2: return InGame;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TeamMemberState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TeamMemberState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TeamMemberState>() {
          public TeamMemberState findValueByNumber(int number) {
            return TeamMemberState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.zqproto.core.Core.getDescriptor().getEnumTypes().get(1);
  }

  private static final TeamMemberState[] VALUES = values();

  public static TeamMemberState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TeamMemberState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:core.TeamMemberState)
}

