// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/userdef.proto

package com.proto.user;

public interface GetUserPLevelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUserPLevelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.comm.ErrorType code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.comm.ErrorType code = 1;</code>
   * @return The code.
   */
  com.proto.comm.ErrorType getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 用户等级信息
   * </pre>
   *
   * <code>.user.PLevelInfo level = 3;</code>
   * @return Whether the level field is set.
   */
  boolean hasLevel();
  /**
   * <pre>
   * 用户等级信息
   * </pre>
   *
   * <code>.user.PLevelInfo level = 3;</code>
   * @return The level.
   */
  com.proto.user.PLevelInfo getLevel();
  /**
   * <pre>
   * 用户等级信息
   * </pre>
   *
   * <code>.user.PLevelInfo level = 3;</code>
   */
  com.proto.user.PLevelInfoOrBuilder getLevelOrBuilder();

  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 4;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 4;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
