// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/userdef.proto

package com.proto.user;

public interface GetUserInfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUserInfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.comm.ErrorType code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.comm.ErrorType code = 1;</code>
   * @return The code.
   */
  com.proto.comm.ErrorType getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>repeated .user.UserInfo user = 3;</code>
   */
  java.util.List<com.proto.user.UserInfo> 
      getUserList();
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>repeated .user.UserInfo user = 3;</code>
   */
  com.proto.user.UserInfo getUser(int index);
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>repeated .user.UserInfo user = 3;</code>
   */
  int getUserCount();
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>repeated .user.UserInfo user = 3;</code>
   */
  java.util.List<? extends com.proto.user.UserInfoOrBuilder> 
      getUserOrBuilderList();
  /**
   * <pre>
   * 用户信息
   * </pre>
   *
   * <code>repeated .user.UserInfo user = 3;</code>
   */
  com.proto.user.UserInfoOrBuilder getUserOrBuilder(
      int index);

  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceid = 4;</code>
   * @return The traceid.
   */
  java.lang.String getTraceid();
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceid = 4;</code>
   * @return The bytes for traceid.
   */
  com.google.protobuf.ByteString
      getTraceidBytes();

  /**
   * <pre>
   * 第三方游戏账号信息，需要接收方转换成对应的结构体
   * </pre>
   *
   * <code>map&lt;string, string&gt; thirdAccount = 5;</code>
   */
  int getThirdAccountCount();
  /**
   * <pre>
   * 第三方游戏账号信息，需要接收方转换成对应的结构体
   * </pre>
   *
   * <code>map&lt;string, string&gt; thirdAccount = 5;</code>
   */
  boolean containsThirdAccount(
      java.lang.String key);
  /**
   * Use {@link #getThirdAccountMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getThirdAccount();
  /**
   * <pre>
   * 第三方游戏账号信息，需要接收方转换成对应的结构体
   * </pre>
   *
   * <code>map&lt;string, string&gt; thirdAccount = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getThirdAccountMap();
  /**
   * <pre>
   * 第三方游戏账号信息，需要接收方转换成对应的结构体
   * </pre>
   *
   * <code>map&lt;string, string&gt; thirdAccount = 5;</code>
   */

  java.lang.String getThirdAccountOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * 第三方游戏账号信息，需要接收方转换成对应的结构体
   * </pre>
   *
   * <code>map&lt;string, string&gt; thirdAccount = 5;</code>
   */

  java.lang.String getThirdAccountOrThrow(
      java.lang.String key);
}
