// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/userdef.proto

package com.proto.user;

public interface GetUserPLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUserPLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 要获取的用户id, 如果没有则取自己
   * </pre>
   *
   * <code>uint32 target_uid = 1;</code>
   * @return The targetUid.
   */
  int getTargetUid();

  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 2;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 2;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
