// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/userdef.proto

package com.proto.user;

/**
 * <pre>
 * 用户登录通知给所有网关
 * </pre>
 *
 * Protobuf type {@code user.LoginNotify}
 */
public  final class LoginNotify extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.LoginNotify)
    LoginNotifyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoginNotify.newBuilder() to construct.
  private LoginNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoginNotify() {
    currentGateIp_ = "";
    traceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LoginNotify();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LoginNotify(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.proto.user.OneUser.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.proto.user.OneUser.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            loginTime_ = input.readInt64();
            break;
          }
          case 24: {

            socketId_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            currentGateIp_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            traceId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.user.User.internal_static_user_LoginNotify_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.user.User.internal_static_user_LoginNotify_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.user.LoginNotify.class, com.proto.user.LoginNotify.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private com.proto.user.OneUser user_;
  /**
   * <code>.user.OneUser user = 1;</code>
   * @return Whether the user field is set.
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.user.OneUser user = 1;</code>
   * @return The user.
   */
  public com.proto.user.OneUser getUser() {
    return user_ == null ? com.proto.user.OneUser.getDefaultInstance() : user_;
  }
  /**
   * <code>.user.OneUser user = 1;</code>
   */
  public com.proto.user.OneUserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int LOGINTIME_FIELD_NUMBER = 2;
  private long loginTime_;
  /**
   * <code>int64 loginTime = 2;</code>
   * @return The loginTime.
   */
  public long getLoginTime() {
    return loginTime_;
  }

  public static final int SOCKETID_FIELD_NUMBER = 3;
  private int socketId_;
  /**
   * <code>uint32 socketId = 3;</code>
   * @return The socketId.
   */
  public int getSocketId() {
    return socketId_;
  }

  public static final int CURRENTGATEIP_FIELD_NUMBER = 4;
  private volatile java.lang.Object currentGateIp_;
  /**
   * <pre>
   * 当前登录的网关ip
   * </pre>
   *
   * <code>string currentGateIp = 4;</code>
   * @return The currentGateIp.
   */
  public java.lang.String getCurrentGateIp() {
    java.lang.Object ref = currentGateIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentGateIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 当前登录的网关ip
   * </pre>
   *
   * <code>string currentGateIp = 4;</code>
   * @return The bytes for currentGateIp.
   */
  public com.google.protobuf.ByteString
      getCurrentGateIpBytes() {
    java.lang.Object ref = currentGateIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentGateIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACEID_FIELD_NUMBER = 5;
  private volatile java.lang.Object traceId_;
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 5;</code>
   * @return The traceId.
   */
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 5;</code>
   * @return The bytes for traceId.
   */
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    if (loginTime_ != 0L) {
      output.writeInt64(2, loginTime_);
    }
    if (socketId_ != 0) {
      output.writeUInt32(3, socketId_);
    }
    if (!getCurrentGateIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currentGateIp_);
    }
    if (!getTraceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, traceId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    if (loginTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, loginTime_);
    }
    if (socketId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, socketId_);
    }
    if (!getCurrentGateIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currentGateIp_);
    }
    if (!getTraceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, traceId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.user.LoginNotify)) {
      return super.equals(obj);
    }
    com.proto.user.LoginNotify other = (com.proto.user.LoginNotify) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (getLoginTime()
        != other.getLoginTime()) return false;
    if (getSocketId()
        != other.getSocketId()) return false;
    if (!getCurrentGateIp()
        .equals(other.getCurrentGateIp())) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (37 * hash) + LOGINTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLoginTime());
    hash = (37 * hash) + SOCKETID_FIELD_NUMBER;
    hash = (53 * hash) + getSocketId();
    hash = (37 * hash) + CURRENTGATEIP_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentGateIp().hashCode();
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.user.LoginNotify parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.user.LoginNotify parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.user.LoginNotify parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.user.LoginNotify parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.user.LoginNotify parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.user.LoginNotify parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.user.LoginNotify parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.user.LoginNotify parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.user.LoginNotify parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.user.LoginNotify parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.user.LoginNotify parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.user.LoginNotify parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.user.LoginNotify prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户登录通知给所有网关
   * </pre>
   *
   * Protobuf type {@code user.LoginNotify}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.LoginNotify)
      com.proto.user.LoginNotifyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.user.User.internal_static_user_LoginNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.user.User.internal_static_user_LoginNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.user.LoginNotify.class, com.proto.user.LoginNotify.Builder.class);
    }

    // Construct using com.proto.user.LoginNotify.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      loginTime_ = 0L;

      socketId_ = 0;

      currentGateIp_ = "";

      traceId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.user.User.internal_static_user_LoginNotify_descriptor;
    }

    @java.lang.Override
    public com.proto.user.LoginNotify getDefaultInstanceForType() {
      return com.proto.user.LoginNotify.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.user.LoginNotify build() {
      com.proto.user.LoginNotify result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.user.LoginNotify buildPartial() {
      com.proto.user.LoginNotify result = new com.proto.user.LoginNotify(this);
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      result.loginTime_ = loginTime_;
      result.socketId_ = socketId_;
      result.currentGateIp_ = currentGateIp_;
      result.traceId_ = traceId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.user.LoginNotify) {
        return mergeFrom((com.proto.user.LoginNotify)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.user.LoginNotify other) {
      if (other == com.proto.user.LoginNotify.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.getLoginTime() != 0L) {
        setLoginTime(other.getLoginTime());
      }
      if (other.getSocketId() != 0) {
        setSocketId(other.getSocketId());
      }
      if (!other.getCurrentGateIp().isEmpty()) {
        currentGateIp_ = other.currentGateIp_;
        onChanged();
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.user.LoginNotify parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.user.LoginNotify) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.proto.user.OneUser user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.user.OneUser, com.proto.user.OneUser.Builder, com.proto.user.OneUserOrBuilder> userBuilder_;
    /**
     * <code>.user.OneUser user = 1;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     * @return The user.
     */
    public com.proto.user.OneUser getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.proto.user.OneUser.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     */
    public Builder setUser(com.proto.user.OneUser value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     */
    public Builder setUser(
        com.proto.user.OneUser.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     */
    public Builder mergeUser(com.proto.user.OneUser value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.proto.user.OneUser.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     */
    public com.proto.user.OneUser.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     */
    public com.proto.user.OneUserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.proto.user.OneUser.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.user.OneUser user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.user.OneUser, com.proto.user.OneUser.Builder, com.proto.user.OneUserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.proto.user.OneUser, com.proto.user.OneUser.Builder, com.proto.user.OneUserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private long loginTime_ ;
    /**
     * <code>int64 loginTime = 2;</code>
     * @return The loginTime.
     */
    public long getLoginTime() {
      return loginTime_;
    }
    /**
     * <code>int64 loginTime = 2;</code>
     * @param value The loginTime to set.
     * @return This builder for chaining.
     */
    public Builder setLoginTime(long value) {
      
      loginTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 loginTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginTime() {
      
      loginTime_ = 0L;
      onChanged();
      return this;
    }

    private int socketId_ ;
    /**
     * <code>uint32 socketId = 3;</code>
     * @return The socketId.
     */
    public int getSocketId() {
      return socketId_;
    }
    /**
     * <code>uint32 socketId = 3;</code>
     * @param value The socketId to set.
     * @return This builder for chaining.
     */
    public Builder setSocketId(int value) {
      
      socketId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 socketId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketId() {
      
      socketId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object currentGateIp_ = "";
    /**
     * <pre>
     * 当前登录的网关ip
     * </pre>
     *
     * <code>string currentGateIp = 4;</code>
     * @return The currentGateIp.
     */
    public java.lang.String getCurrentGateIp() {
      java.lang.Object ref = currentGateIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentGateIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 当前登录的网关ip
     * </pre>
     *
     * <code>string currentGateIp = 4;</code>
     * @return The bytes for currentGateIp.
     */
    public com.google.protobuf.ByteString
        getCurrentGateIpBytes() {
      java.lang.Object ref = currentGateIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentGateIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 当前登录的网关ip
     * </pre>
     *
     * <code>string currentGateIp = 4;</code>
     * @param value The currentGateIp to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentGateIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentGateIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前登录的网关ip
     * </pre>
     *
     * <code>string currentGateIp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentGateIp() {
      
      currentGateIp_ = getDefaultInstance().getCurrentGateIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前登录的网关ip
     * </pre>
     *
     * <code>string currentGateIp = 4;</code>
     * @param value The bytes for currentGateIp to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentGateIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentGateIp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 5;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 5;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 5;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      
      traceId_ = getDefaultInstance().getTraceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户的uuid，用来追踪用户消息链路
     * </pre>
     *
     * <code>string traceId = 5;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:user.LoginNotify)
  }

  // @@protoc_insertion_point(class_scope:user.LoginNotify)
  private static final com.proto.user.LoginNotify DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.user.LoginNotify();
  }

  public static com.proto.user.LoginNotify getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginNotify>
      PARSER = new com.google.protobuf.AbstractParser<LoginNotify>() {
    @java.lang.Override
    public LoginNotify parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LoginNotify(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoginNotify> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginNotify> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.user.LoginNotify getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

