// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/userdef.proto

package com.proto.user;

public interface LoginNotifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.LoginNotify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.user.OneUser user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.user.OneUser user = 1;</code>
   * @return The user.
   */
  com.proto.user.OneUser getUser();
  /**
   * <code>.user.OneUser user = 1;</code>
   */
  com.proto.user.OneUserOrBuilder getUserOrBuilder();

  /**
   * <code>int64 loginTime = 2;</code>
   * @return The loginTime.
   */
  long getLoginTime();

  /**
   * <code>uint32 socketId = 3;</code>
   * @return The socketId.
   */
  int getSocketId();

  /**
   * <pre>
   * 当前登录的网关ip
   * </pre>
   *
   * <code>string currentGateIp = 4;</code>
   * @return The currentGateIp.
   */
  java.lang.String getCurrentGateIp();
  /**
   * <pre>
   * 当前登录的网关ip
   * </pre>
   *
   * <code>string currentGateIp = 4;</code>
   * @return The bytes for currentGateIp.
   */
  com.google.protobuf.ByteString
      getCurrentGateIpBytes();

  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 5;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * 用户的uuid，用来追踪用户消息链路
   * </pre>
   *
   * <code>string traceId = 5;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
