// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/userdef.proto

package com.proto.user;

/**
 * <pre>
 * 用户等级信息
 * </pre>
 *
 * Protobuf type {@code user.PLevelInfo}
 */
public  final class PLevelInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.PLevelInfo)
    PLevelInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PLevelInfo.newBuilder() to construct.
  private PLevelInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PLevelInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PLevelInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PLevelInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            level_ = input.readUInt32();
            break;
          }
          case 16: {

            exp_ = input.readUInt32();
            break;
          }
          case 24: {

            left_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.user.User.internal_static_user_PLevelInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.user.User.internal_static_user_PLevelInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.user.PLevelInfo.class, com.proto.user.PLevelInfo.Builder.class);
  }

  public static final int LEVEL_FIELD_NUMBER = 1;
  private int level_;
  /**
   * <pre>
   * 当前的用户等级
   * </pre>
   *
   * <code>uint32 level = 1;</code>
   * @return The level.
   */
  public int getLevel() {
    return level_;
  }

  public static final int EXP_FIELD_NUMBER = 2;
  private int exp_;
  /**
   * <pre>
   * 当前的等级经验
   * </pre>
   *
   * <code>uint32 exp = 2;</code>
   * @return The exp.
   */
  public int getExp() {
    return exp_;
  }

  public static final int LEFT_FIELD_NUMBER = 3;
  private int left_;
  /**
   * <pre>
   * 升级到下一等级需要的经验
   * </pre>
   *
   * <code>uint32 left = 3;</code>
   * @return The left.
   */
  public int getLeft() {
    return left_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (level_ != 0) {
      output.writeUInt32(1, level_);
    }
    if (exp_ != 0) {
      output.writeUInt32(2, exp_);
    }
    if (left_ != 0) {
      output.writeUInt32(3, left_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, level_);
    }
    if (exp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, exp_);
    }
    if (left_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, left_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.user.PLevelInfo)) {
      return super.equals(obj);
    }
    com.proto.user.PLevelInfo other = (com.proto.user.PLevelInfo) obj;

    if (getLevel()
        != other.getLevel()) return false;
    if (getExp()
        != other.getExp()) return false;
    if (getLeft()
        != other.getLeft()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + EXP_FIELD_NUMBER;
    hash = (53 * hash) + getExp();
    hash = (37 * hash) + LEFT_FIELD_NUMBER;
    hash = (53 * hash) + getLeft();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.user.PLevelInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.user.PLevelInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.user.PLevelInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.user.PLevelInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.user.PLevelInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.user.PLevelInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.user.PLevelInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.user.PLevelInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.user.PLevelInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.user.PLevelInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.user.PLevelInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.user.PLevelInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.user.PLevelInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户等级信息
   * </pre>
   *
   * Protobuf type {@code user.PLevelInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.PLevelInfo)
      com.proto.user.PLevelInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.user.User.internal_static_user_PLevelInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.user.User.internal_static_user_PLevelInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.user.PLevelInfo.class, com.proto.user.PLevelInfo.Builder.class);
    }

    // Construct using com.proto.user.PLevelInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      level_ = 0;

      exp_ = 0;

      left_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.user.User.internal_static_user_PLevelInfo_descriptor;
    }

    @java.lang.Override
    public com.proto.user.PLevelInfo getDefaultInstanceForType() {
      return com.proto.user.PLevelInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.user.PLevelInfo build() {
      com.proto.user.PLevelInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.user.PLevelInfo buildPartial() {
      com.proto.user.PLevelInfo result = new com.proto.user.PLevelInfo(this);
      result.level_ = level_;
      result.exp_ = exp_;
      result.left_ = left_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.user.PLevelInfo) {
        return mergeFrom((com.proto.user.PLevelInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.user.PLevelInfo other) {
      if (other == com.proto.user.PLevelInfo.getDefaultInstance()) return this;
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (other.getExp() != 0) {
        setExp(other.getExp());
      }
      if (other.getLeft() != 0) {
        setLeft(other.getLeft());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.user.PLevelInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.user.PLevelInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int level_ ;
    /**
     * <pre>
     * 当前的用户等级
     * </pre>
     *
     * <code>uint32 level = 1;</code>
     * @return The level.
     */
    public int getLevel() {
      return level_;
    }
    /**
     * <pre>
     * 当前的用户等级
     * </pre>
     *
     * <code>uint32 level = 1;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {
      
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前的用户等级
     * </pre>
     *
     * <code>uint32 level = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      
      level_ = 0;
      onChanged();
      return this;
    }

    private int exp_ ;
    /**
     * <pre>
     * 当前的等级经验
     * </pre>
     *
     * <code>uint32 exp = 2;</code>
     * @return The exp.
     */
    public int getExp() {
      return exp_;
    }
    /**
     * <pre>
     * 当前的等级经验
     * </pre>
     *
     * <code>uint32 exp = 2;</code>
     * @param value The exp to set.
     * @return This builder for chaining.
     */
    public Builder setExp(int value) {
      
      exp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前的等级经验
     * </pre>
     *
     * <code>uint32 exp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExp() {
      
      exp_ = 0;
      onChanged();
      return this;
    }

    private int left_ ;
    /**
     * <pre>
     * 升级到下一等级需要的经验
     * </pre>
     *
     * <code>uint32 left = 3;</code>
     * @return The left.
     */
    public int getLeft() {
      return left_;
    }
    /**
     * <pre>
     * 升级到下一等级需要的经验
     * </pre>
     *
     * <code>uint32 left = 3;</code>
     * @param value The left to set.
     * @return This builder for chaining.
     */
    public Builder setLeft(int value) {
      
      left_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 升级到下一等级需要的经验
     * </pre>
     *
     * <code>uint32 left = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeft() {
      
      left_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:user.PLevelInfo)
  }

  // @@protoc_insertion_point(class_scope:user.PLevelInfo)
  private static final com.proto.user.PLevelInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.user.PLevelInfo();
  }

  public static com.proto.user.PLevelInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PLevelInfo>
      PARSER = new com.google.protobuf.AbstractParser<PLevelInfo>() {
    @java.lang.Override
    public PLevelInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PLevelInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PLevelInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PLevelInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.user.PLevelInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

