// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/userdef.proto

package com.proto.user;

public interface PLevelInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.PLevelInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 当前的用户等级
   * </pre>
   *
   * <code>uint32 level = 1;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * 当前的等级经验
   * </pre>
   *
   * <code>uint32 exp = 2;</code>
   * @return The exp.
   */
  int getExp();

  /**
   * <pre>
   * 升级到下一等级需要的经验
   * </pre>
   *
   * <code>uint32 left = 3;</code>
   * @return The left.
   */
  int getLeft();
}
