// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comm/common.proto

package com.proto.comm;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:comm.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>.comm.ErrorType code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>.comm.ErrorType code = 1;</code>
   * @return The code.
   */
  com.proto.comm.ErrorType getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
